<?php
// FILE: src/master/maintenance/system_health.php
session_start();
require_once __DIR__ . '/../../config/database.php';

// PROTEKSI AKSES
if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'master') {
    header("Location: ../../../public/login.php"); exit;
}

// ==========================================
// 1. LOGIKA BACKUP DATABASE (PURE PHP)
// ==========================================
if (isset($_POST['download_backup'])) {
    
    $tables = [];
    $stmt = $pdo->query("SHOW TABLES");
    while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
        $tables[] = $row[0];
    }

    $sqlScript = "-- DATABASE BACKUP: swim_meet\n";
    $sqlScript .= "-- DATE: " . date('Y-m-d H:i:s') . "\n";
    $sqlScript .= "-- GENERATED BY: Master Admin\n\n";
    $sqlScript .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
    $sqlScript .= "START TRANSACTION;\n";
    $sqlScript .= "SET time_zone = \"+00:00\";\n\n";

    foreach ($tables as $table) {
        // A. Struktur Tabel
        $row = $pdo->query("SHOW CREATE TABLE $table")->fetch(PDO::FETCH_NUM);
        $sqlScript .= "\n\n" . $row[1] . ";\n\n";

        // B. Isi Data
        $stmtData = $pdo->query("SELECT * FROM $table");
        $columnCount = $stmtData->columnCount();

        while ($row = $stmtData->fetch(PDO::FETCH_NUM)) {
            $sqlScript .= "INSERT INTO $table VALUES(";
            for ($j = 0; $j < $columnCount; $j++) {
                $row[$j] = addslashes($row[$j]);
                $row[$j] = str_replace("\n", "\\n", $row[$j]);
                if (isset($row[$j])) {
                    $sqlScript .= '"' . $row[$j] . '"';
                } else {
                    $sqlScript .= '""';
                }
                if ($j < ($columnCount - 1)) {
                    $sqlScript .= ',';
                }
            }
            $sqlScript .= ");\n";
        }
    }
    $sqlScript .= "\nCOMMIT;\n";

    // Download File
    $filename = 'backup_swimmeet_' . date('Y-m-d_His') . '.sql';
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename=' . $filename);
    echo $sqlScript;
    exit; // Stop script agar HTML di bawah tidak ikut ter-download
}

// ==========================================
// 2. LOGIKA VIEW LOGS
// ==========================================
// Pagination sederhana
$limit = 50;
$page = isset($_GET['page']) ? (int)$_GET['page'] : 1;
$offset = ($page - 1) * $limit;

// Query Log + Join User
$sqlLogs = "SELECT l.*, u.nama_lengkap, u.role 
            FROM system_logs l 
            LEFT JOIN users u ON l.user_id = u.id 
            ORDER BY l.created_at DESC 
            LIMIT :limit OFFSET :offset";
$stmt = $pdo->prepare($sqlLogs);
$stmt->bindValue(':limit', $limit, PDO::PARAM_INT);
$stmt->bindValue(':offset', $offset, PDO::PARAM_INT);
$stmt->execute();
$logs = $stmt->fetchAll();

// Hitung Total Log
$totalLogs = $pdo->query("SELECT COUNT(*) FROM system_logs")->fetchColumn();
$totalPages = ceil($totalLogs / $limit);

include __DIR__ . '/../../../views/layout/sidebar.php';
include __DIR__ . '/../../../views/layout/topbar.php';
?>

<div class="p-6 sm:ml-64 pt-24 bg-slate-50 min-h-screen font-sans">

    <div class="mb-8 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
            <h1 class="text-3xl font-black text-slate-800 uppercase italic tracking-tighter">
                System Health & Security
            </h1>
            <p class="text-sm text-slate-500 font-medium">Backup database dan pantau aktivitas sistem.</p>
        </div>
        
        <form method="POST">
            <input type="hidden" name="download_backup" value="1">
            <button type="submit" class="bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-3 rounded-xl font-black uppercase text-xs tracking-widest shadow-lg transition transform hover:-translate-y-1 flex items-center gap-2">
                <span>💾</span> Download Backup Database
            </button>
        </form>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div class="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
            <div class="text-[10px] font-black uppercase text-slate-400 tracking-widest mb-1">Total Aktivitas</div>
            <div class="text-3xl font-black text-slate-800"><?= number_format($totalLogs) ?></div>
            <div class="text-xs text-slate-500">Log tercatat di sistem</div>
        </div>
        <div class="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
            <div class="text-[10px] font-black uppercase text-slate-400 tracking-widest mb-1">Aktivitas Hari Ini</div>
            <?php 
                $todayLog = $pdo->query("SELECT COUNT(*) FROM system_logs WHERE DATE(created_at) = CURDATE()")->fetchColumn();
            ?>
            <div class="text-3xl font-black text-blue-600"><?= $todayLog ?></div>
            <div class="text-xs text-slate-500">Aksi dilakukan hari ini</div>
        </div>
        <div class="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
            <div class="text-[10px] font-black uppercase text-slate-400 tracking-widest mb-1">Ukuran Database</div>
            <?php 
                // Hitung estimasi ukuran DB (khusus MySQL)
                try {
                    $sqlSize = "SELECT table_schema 'DB Name', ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) 'Size in MB' FROM information_schema.tables WHERE table_schema = DATABASE() GROUP BY table_schema";
                    $dbSize = $pdo->query($sqlSize)->fetchColumn(1);
                } catch(Exception $e) { $dbSize = '0'; }
            ?>
            <div class="text-3xl font-black text-emerald-600"><?= $dbSize ?> <span class="text-sm text-slate-400">MB</span></div>
            <div class="text-xs text-slate-500">Estimasi penggunaan disk</div>
        </div>
    </div>

    <div class="bg-white rounded-[2rem] shadow-xl border border-slate-200 overflow-hidden">
        <div class="bg-slate-800 px-8 py-5 border-b border-slate-700 flex justify-between items-center">
            <h3 class="text-white font-black text-sm uppercase tracking-wider flex items-center gap-2">
                📜 Audit Trail (Log Aktivitas)
            </h3>
            <div class="text-slate-400 text-[10px] font-bold uppercase">Halaman <?= $page ?> dari <?= $totalPages ?></div>
        </div>
        
        <div class="overflow-x-auto">
            <table class="w-full text-left text-sm">
                <thead class="bg-slate-50 text-[10px] uppercase text-slate-500 font-bold border-b border-slate-200">
                    <tr>
                        <th class="px-6 py-4">Waktu</th>
                        <th class="px-6 py-4">User / Aktor</th>
                        <th class="px-6 py-4">Tipe Aksi</th>
                        <th class="px-6 py-4">Deskripsi</th>
                        <th class="px-6 py-4">IP Address</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-100">
                    <?php if(empty($logs)): ?>
                        <tr><td colspan="5" class="p-8 text-center text-slate-400 italic">Belum ada aktivitas tercatat.</td></tr>
                    <?php else: foreach($logs as $log): ?>
                        <tr class="hover:bg-blue-50/50 transition">
                            <td class="px-6 py-3 whitespace-nowrap text-xs font-mono text-slate-500">
                                <?= date('d/m/Y H:i', strtotime($log['created_at'])) ?>
                            </td>
                            <td class="px-6 py-3">
                                <div class="font-bold text-slate-800 text-xs">
                                    <?= htmlspecialchars($log['nama_lengkap'] ?? 'Unknown/Deleted') ?>
                                </div>
                                <span class="text-[9px] uppercase px-1.5 py-0.5 rounded bg-slate-100 text-slate-500 border border-slate-200">
                                    <?= htmlspecialchars($log['role'] ?? 'System') ?>
                                </span>
                            </td>
                            <td class="px-6 py-3">
                                <?php 
                                    // Warna Badge Berdasarkan Tipe Aksi
                                    $action = $log['action_type'];
                                    $color = 'bg-slate-100 text-slate-600';
                                    if(strpos($action, 'DELETE') !== false) $color = 'bg-red-50 text-red-600 border-red-100';
                                    elseif(strpos($action, 'CREATE') !== false) $color = 'bg-emerald-50 text-emerald-600 border-emerald-100';
                                    elseif(strpos($action, 'UPDATE') !== false || strpos($action, 'EDIT') !== false) $color = 'bg-blue-50 text-blue-600 border-blue-100';
                                    elseif(strpos($action, 'LOGIN') !== false) $color = 'bg-purple-50 text-purple-600 border-purple-100';
                                ?>
                                <span class="px-2 py-1 rounded border text-[10px] font-black uppercase tracking-wide <?= $color ?>">
                                    <?= htmlspecialchars($action) ?>
                                </span>
                            </td>
                            <td class="px-6 py-3 text-xs text-slate-600 font-medium">
                                <?= htmlspecialchars($log['description']) ?>
                                <?php if($log['target_id'] != 0): ?>
                                    <span class="text-slate-400 text-[10px] ml-1">(ID: <?= $log['target_id'] ?>)</span>
                                <?php endif; ?>
                            </td>
                            <td class="px-6 py-3 text-[10px] font-mono text-slate-400">
                                <?= htmlspecialchars($log['ip_address']) ?>
                            </td>
                        </tr>
                    <?php endforeach; endif; ?>
                </tbody>
            </table>
        </div>
        
        <?php if($totalPages > 1): ?>
        <div class="p-4 border-t border-slate-200 bg-slate-50 flex justify-center gap-2">
            <?php if($page > 1): ?>
                <a href="?page=<?= $page - 1 ?>" class="px-3 py-1 bg-white border border-slate-300 rounded text-xs hover:bg-slate-100">← Prev</a>
            <?php endif; ?>
            
            <?php for($i=1; $i<=$totalPages; $i++): ?>
                <a href="?page=<?= $i ?>" class="px-3 py-1 border rounded text-xs <?= $i == $page ? 'bg-slate-800 text-white border-slate-800' : 'bg-white border-slate-300 hover:bg-slate-100' ?>">
                    <?= $i ?>
                </a>
            <?php endfor; ?>
            
            <?php if($page < $totalPages): ?>
                <a href="?page=<?= $page + 1 ?>" class="px-3 py-1 bg-white border border-slate-300 rounded text-xs hover:bg-slate-100">Next →</a>
            <?php endif; ?>
        </div>
        <?php endif; ?>

    </div>
</div>